name: test_task_balina_soft
description: "Test Task BalinaSoft"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.6
  dio: ^5.7.0
  json_annotation: ^4.9.0
  yandex_maps_mapkit_lite: ^4.9.0-beta
  image_picker: ^1.1.2
  native_exif: ^0.6.0
  shared_preferences: ^2.3.3
  pretty_dio_logger: ^1.4.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  json_serializable: ^6.8.0

flutter:
  assets:
    - assets/
  uses-material-design: true
  generate: true
